### ISSUE TITLE
Links to Demo/Playground/Widget Browser only available when scrolled to bottom

### ISSUE THREAD

**Issue by rad-pat** [qooxdoo/website#27]
I found it a little annoying to have to scroll to the bottom of the home page to get to the links for demo / playground / widget browser. There are drop down menus for the Documentation and the Community an the top of the page so it would seem sense to add some menu/links to get to these other resources without having to scroll to the bottom

**Comment by cboulanger** [comment]
Done with 20b4e1f1f9da3bec24c9606f28bc5ca9147f508c.
