### ISSUE TITLE
png for companies logo in the landing page 

### ISSUE THREAD

**Issue by slachtar** [qooxdoo/website#5]
I think using png for companies logo in http://www.qooxdoo.org/website/ will give a better look.

**Comment by cboulanger** [comment]
Would you consider cloning the repo and replacing the logos? That would help us alot!

**Comment by cboulanger** [comment]
You could combine this with adding an entry to the portfolio (see https://github.com/qooxdoo/qooxdoo/issues/9814#issuecomment-620423214) - I don't think there is one yet?

**Comment by hkollmann** [comment]
all logos are png now
